[versions]
## plugins version
androidPlugin = "7.4.1"
kotlinPlugin = "1.8.10"
ktlintPlugin = "11.4.2"
hiltPlugin = "2.44"

## androidx
androidx-core-ktx = "1.8.0"
androidx-lifecycle = "2.5.1"
androidx-lifecycle-compose = "2.6.0"
androidx-activity-compose = "1.5.1"
androidx-compose-bom = "2023.06.00"
androidx-navigation-compose = "2.5.3"
androidx-datastore-preference = "1.0.0"
androidx-hilt-navigation-compose = "1.0.0"
androidx-splashscreen = "1.0.0"

## hilt
hilt = "2.44"

## timber
timber = "5.0.1"

## 3rd library
coil-compose = "2.4.0"
barcode-scanning = "17.2.0"

## retrofit2
retrofit2 = "2.9.0"
logging-interceptor = "4.11.0"

## coroutine
coroutine-core = "1.6.4"

## kakao
kakao = "2.18.0"
kakao-map = "2.6.0"

## naver-map
naver-map-compose = "1.3.3"

## test
junit = "4.13.2"
androidx-junit = "1.1.5"
androidx-espresso-core = "3.5.1"
appcompat = "1.6.1"
material = "1.9.0"
accompanist-compose = "0.31.5-beta"

[plugins]
android-application = { id = "com.android.application", version.ref = "androidPlugin" }
android-library = { id = "com.android.library", version.ref = "androidPlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinPlugin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlinPlugin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintPlugin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hiltPlugin" }

[libraries]
## androidx
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity-compose" }
androidx-lifecycle-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle-compose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidx-compose-bom" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidx-navigation-compose" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidx-hilt-navigation-compose" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidx-datastore-preference" }
androidx-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidx-splashscreen" }

## hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }

## timber
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

## accompanist
accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist-compose" }
accompanist-pager = { group = "com.google.accompanist", name = "accompanist-pager", version.ref = "accompanist-compose" }
accompanist-pager-indicators = { group = "com.google.accompanist", name = "accompanist-pager-indicators", version.ref = "accompanist-compose" }
accompanist-webview = { group = "com.google.accompanist", name = "accompanist-webview", version.ref = "accompanist-compose" }

## 3rd library
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil-compose" }
barcode-scanning = { group = "com.google.mlkit", name = "barcode-scanning", version.ref = "barcode-scanning" }

## retrofit2
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit2" }
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit2" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "logging-interceptor" }

## coroutine
coroutine-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutine-core" }

## kakao
kakao-user = { group = "com.kakao.sdk", name = "v2-user", version.ref = "kakao" }
kakao-map = { group = "com.kakao.maps.open", name = "android", version.ref = "kakao-map" }

## naver-map
naver-map-compose = { group = "io.github.fornewid", name = "naver-map-compose", version.ref = "naver-map-compose" }

## test
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso-core" }
androidx-compose-ui-test-junit = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[bundles]
androidx-compose = ["androidx-compose-ui", "androidx-compose-ui-tooling", "androidx-compose-ui-tooling-preview", "androidx-activity-compose", "androidx-compose-material3", "androidx-navigation-compose", "androidx-lifecycle-compose", "androidx-hilt-navigation-compose"]
retrofit = ["retrofit", "converter-gson", "logging-interceptor"]